version: '2'
services:
    crmadmin-app:
        image: crmadmin
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://crmadmin-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=crmAdmin
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    crmadmin-mongodb:
        extends:
            file: mongodb.yml
            service: crmadmin-mongodb
