export const ITEMS_PER_PAGE = 1;
export const LANGUAGES: string[] = ['Avestan', 'Afrikaans', 'Albanian', 'Armenian', 'Aragonese', 'Arabic', 'Assamese', 'Azerbaijani', 'Bashkir', 'Belarusian',
'Bulgarian', 'Bihari', 'Bislama', 'Bambara', 'Bengali', 'Tibetan Standard', 'Breton', 'Bosnian', 'Catalan', 'Chamorro',
'Chinese', 'Corsican', 'Cree', 'Czech', 'Chuvash', 'Welsh', 'German', 'Danish', 'Dzongkha', 'Ewe', 'English', 'Spanish',
'Estonian', 'Finnish', 'Fijian', 'Faroese', 'French', 'Irish', 'Gaelic', 'Georgian', 'Galician', 'Guarana', 'Greek',
'Gujarati', 'Croatian', 'Haitian', 'Hungarian', 'Indonesian', 'Hebrew', 'Hindi', 'Ido', 'Persian', 'Icelandic',
'Italian', 'Japanese', 'Kongo', 'Kikuyu', 'Khmer', 'Kannada', 'Korean', 'Kyrgyz', 'Luxembourgish', 'Limburgish',
'Lithuanian', 'Latvian', 'Malagasy', 'Marshallese', 'Macedonian', 'Malayalam', 'Mongolian', 'Malay', 'Maltese',
'Burmese', 'Nauru', 'Nepali', 'Ndonga', 'Dutch', 'Norwegian', 'Southern Ndebele', 'Oromo', 'Punjabi', 'Urdu', 'Polish',
'Pashto', 'Portuguese', 'Romanian', 'Russian', 'Kinyarwanda', 'Sanskrit', 'Sardinian', 'Sindhi', 'Northern Sami',
'Sango', 'Sinhala', 'Slovak', 'Slovene', 'Samoan', 'Shona', 'Somali', 'Serbian', 'Southern Sotho', 'Swedish', 'Tajik',
'Thai', 'Turkmen', 'Tagalog', 'Tswana', 'Tonga', 'Turkish', 'Tatar', 'Twi', 'Uyghur', 'Ukranian', 'Uzbek', 'Venda',
'Vietnamese', 'Zhuang'];
export const TIME_ZONES: string[] = ['Adelaide, Darwin (UTC+9:30)', 'American Samoa (UTC-11)', 'Arizona, Chihuahua, La Paz, Mazatlan (UTC-7)',
'Athens, Beirut, Bucharest, Harare, Istanbul, Pretoria (UTC+2)', 'Auckland, Wellington (UTC+12)', 'Azores (UTC-1)',
'Baker Island, Howland Island (UTC-12)', 'Bangkok, Hanoi, Jakarta (UTC+7)', 'Barbados, Roraima (UTC-4)',
'Beijing, Chongqing, Hong Kong, Perth, Singapore (UTC+8)', 'Berlin, Paris, Rome (UTC+1)', 'Bogota, Lima, Quito (UTC-5)',
'Brasilia, Buenos Aires (UTC-3)', 'Brisbane, Canberra, Melbourne, Sydney (UTC+10)', 'Caracas (UTC-4:30)',
'Central Standard Time (UTC-6)', 'Christmas Islands, Kiribati (UTC+14)', 'Dhaka (UTC+6)', 'Dublin, Lisbon, London (UTC)',
'Eastern Time (UTC-5)', 'Ethiopia, Kenya, Somalia, South Sudan, Tanzania, Uganda (UTC+3)', 'Fernando de Noronha (UTC-2)',
'Hawaii (UTC-10)', 'Iran Standard Time (UTC+3:30)', 'Islamabad, Karachi (UTC+5)', 'Kabul (UTC+4:30)',
'Kolkata, Mumbai, New Delhi (UTC+5:30)', 'Labrador, Newfoundland, Santiago (UTC-3:30)', 'Moscow, Riyadh, St. Petersburg (UTC+4)',
'Mountain Standard Time (UTC-7)', 'Myanmar Standard Time (UTC+6:30)', 'Nepal Standard Time (UTC+5:45)',
'New Caledonia, Solomon Islands, Vanuatu (UTC+11)', 'Osaka, Sapporo, Seoul, Tokyo (UTC+9)',
'Pacific Standard Time (UTC-8)', 'Salmaga Island (UTC-9)', 'Samoa, Tonga (UTC+13)'];
